services:
  web-frontend:
    ports:
    - "8001:8000"
    - "1444:1443"
    environment:
      - TEST_SERVER=1
    volumes:
      - /etc/letsencrypt/live/dev.seung.site/fullchain.pem:/etc/letsencrypt/live/dev.seung.site/fullchain.pem:ro
      - /etc/letsencrypt/live/dev.seung.site/privkey.pem:/etc/letsencrypt/live/dev.seung.site/privkey.pem:ro

