services:
  web-frontend:
    image: registry.copl-dev.site/code-place-dev/frontend:latest
#    pull_policy: always
    environment:
      - FORCE_HTTPS=1
      # - STATIC_CDN_HOST=cdn.oj.com
    volumes:
      - ../frontend/deploy/nginx/log:/data/log

  backend:
    image: registry.copl-dev.site/code-place-dev/backend:latest
    restart: always
#    pull_policy: always
    depends_on:
      - oj-redis
      - oj-postgres
      - oj-judge
    volumes:
      - data_volume:/data:rw
    env_file:
      - .env
    environment:
      - JUDGE_SERVER_TOKEN=CHANGE_THIS # secret.key

  scheduler:
    image: registry.copl-dev.site/code-place-dev/scheduler:latest
    restart: always
#    pull_policy: always
    depends_on:
      - oj-postgres
      - backend
    volumes:
      - ../scheduler/logs:/app/logs
    env_file:
      - .env

  oj-judge:
    image: registry.copl-dev.site/code-place-dev/judge-server:1.0.0-beta
    restart: always
    #    read_only: true
    cap_drop:
      - SETPCAP
      - MKNOD
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP
      - FSETID
    tmpfs:
      - /tmp
    volumes:
      - ../backend/data/backend/test_case:/test_case:ro
      - ../backend/data/judge_server/log:/log
      - ../backend/data/judge_server/run:/judger
    environment:
      - SERVICE_URL=http://oj-judge:8080
      - BACKEND_URL=http://backend:8080/api/judge_server_heartbeat/
      - TOKEN=CHANGE_THIS # secret.key
      # - judger_debug=1

  oj-redis:
    image: redis:4.0-alpine
    restart: always
    volumes:
      - ../backend/data/redis:/data

  oj-postgres:
    image: postgres:10-alpine
    restart: always
    volumes:
      - ../backend/data/postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5437:5432"
