on:
  repository_dispatch:
    types: [trigger-cd]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Update Docker Swarm service
        run: |
          COMPONENT=${{ github.event.client_payload.component }}
          VERSION=${{ github.event.client_payload.version }}
          echo "Updating $COMPONENT service to version $VERSION"
          sudo docker service update --image ${{ secrets.HARBOR_REGISTRY }}/code-place-dev/$COMPONENT:$VERSION $COMPONENT