on:
  workflow_run:
    workflows: ["Change Detection"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'develop' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to production
        run: |
          cd deployment
          chmod +x deploy-prod.sh
          ./deploy-prod.sh
        env:
          DOCKER_HOST: unix:///var/run/docker.sock  