name: Production Pull Request Checks

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch-and-extract-version:
    runs-on: ubuntu-latest
    outputs:
      is_release: ${{ steps.check_name.outputs.is_release }}
      version: ${{ steps.extract_version.outputs.version }}
    steps:
      - name: Check if PR is from a release branch
        id: check_name
        run: |
          if [[ ${{ github.head_ref }} =~ ^release- ]]; then
            echo "is_release=true" >> $GITHUB_OUTPUT
          else
            echo "is_release=false" >> $GITHUB_OUTPUT
          fi

      - name: Extract version from head_ref
        if: steps.check_branch.outputs.is_release == 'true'
        id: extract_version
        run: |
          VERSION=$(echo "${{ github.head_ref }}" | grep -oP 'release-\K[0-9]+\.[0-9]+\.[0-9]+')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  production-pr-notification:
    needs: [check-branch-and-extract-version]
    if: needs.check-branch-and-extract-version.outputs.is_release == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: action-slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          custom_payload: |
            {
              "text": "${{ needs.check-branch-and-extract-version.outputs.version }} 릴리스 테스트 시작",
              "attachments": [
                {
                  "color": "good",
                  "fields": [
                    {
                      "title": "Repository",
                      "value": "${{ github.repository }}",
                      "short": true
                    },
                    {
                      "title": "Commit",
                      "value": "${{ github.sha }}",
                      "short": true
                    },
                    {
                      "title": "Author",
                      "value": "${{ github.actor }}",
                      "short": true
                    },
                    {
                      "title": "Event",
                      "value": "${{ github.event_name }}",
                      "short": true
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
